test:
  adapter: postgresql
  database: tyto_prod
  encoding: unicode
  host: localhost

test:
  adapter: postgresql
  database: tyto_prod
  encoding: unicode
  host: localhost

production:
  adapter: postgresql
  database: tyto_prod
  encoding: unicode
  host: localhost
