development:
  adapter:  postgresql
  database: tyto_dev
  encoding: unicode
  host:     localhost
  username: parthshah
  password:

production:
  adapter: postgresql
  database: tyto_prod
  encoding: unicode
  host: localhost

