development:
  adapter:  postgresql
  database: tyto_dev
  encoding: unicode
  host:     localhost
  username: tyto_admin
  password:

production:
  adapter: postgresql
  database: ar-ex_prod
  encoding: unicode
  host: localhost

