test:
  adapter: sqlite3
  database: tyto_test
  pool: 1
  timeout: 5000

development:
  adapter: postgresql
  database: tyto_dev
  encoding: unicode
  host: localhost
  username:
  password:

production:
  adapter: postgresql
  database: ar-ex_prod
  encoding: unicode
  host: localhost
