test:
  adapter: postgresql
  database: tyto_test
  encoding: unicode
  host: localhost
  username: tyto_admin
  password:

development:
  adapter: postgresql
  database: tyto_dev
  encoding: unicode
  host: localhost
  username: tyto_admin
  password:

production:
  adapter: postgresql
  database: tyto_prod
  encoding: unicode
  host: localhost

